export const objects = [
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
  {toggled: false },
]
